/**
 * Cent-woorden uit cent_woords.pdf
 * Regel: c voor -e, -i en -ij/y wordt /s/
 */
const CENT_WORDS = [
  // pagina 1
  "cent",
  "centrum",
  "centraal",
  "centrale",
  "cel",
  "cello",
  "cellofaan",
  "centimeter",
  "censuur",
  "cement",
  "cederhout",
  "ceremonie",
  "docent",
  "procent",
  "proces",
  "pincet",
  "recept",
  "procedure",
  // pagina 2
  "ambulance",
  "december",
  "specerij",
  "balanceren",
  "produceren",
  "oceaan",
  "citroen",
  "citrusvrucht",
  "cipier",
  "citaat",
  "cinema",
  "cilinder",
  "incident",
  "lucifer",
  "speciaal",
  "specialist",
  "specifiek",
  "principe",
  "feliciteren",
  "felicitatie",
  // pagina 3
  "racisme",
  "emancipatie",
  "medici",
  "musici",
  "politici",
  "narcis",
  "officier",
  "officieel",
  "provincie",
  "cijfer",
  "ontcijferen",
  "medicijn",
  "cycloon",
];
