/**
 * Griekse-y-woorden uit griekse_y_words.pdf
 * De y kan als lolly (lang) of kort (voor twee medeklinkers) klinken
 */
const GRIEKSE_Y_WORDS = [
  // lolly-woorden (lang)
  "lolly",
  "hobby",
  "sorry",
  "teddybeer",
  "buggy",
  "guppy",
  "panty",
  "pony",
  "rugby",
  "jury",
  "pyjama",
  "type",
  "typen",
  "typist",
  "typisch",
  "tyfoon",
  "cycloon",
  // korte y (voor twee medeklinkers)
  "analyse",
  "hyena",
  "dynamo",
  "dynamiet",
  "dynamisch",
  "cyclaam",
  "chrysant",
  "hyacint",
  "mythe",
  "mythisch",
  "labyrint",
  "encyclopedie",
  "systeem",
  "systematisch",
  "synagoge",
  "psychologie",
  "psycholoog",
  "gymmen",
  "gymnastiek",
  "dyslexie",
  "dyslectisch",
  "hygiëne",
  "hygiënisch",
  "symbool",
  "symbolisch",
  "sympathiek",
  "mysterie",
  "mysterius",
  "yoga",
  "yoghurt",
  "yucca",
  "royaal",
  "rayon",
];
